### ISSUE TITLE
"Illegal base time specification" error for some datasets

### ISSUE THREAD

**Issue by tbloch1** [jonathanqv/cmip6d#1]
For some of the datasets, the final date in the year isn't the 31st of December - e.g., for [UKESM1-0-LL](https://ds.nccs.nasa.gov/thredds/ncss/grid/AMES/NEX/GDDP-CMIP6/UKESM1-0-LL/ssp245/r1i1p1f2/pr/pr_day_UKESM1-0-LL_ssp245_r1i1p1f2_gn_2015.nc/dataset.xml) it's 30th of December.

This means that the url generated by the package (something similar to [this](https://ds.nccs.nasa.gov/thredds/ncss/grid/AMES/NEX/GDDP-CMIP6/UKESM1-0-LL/ssp245/r1i1p1f2/pr/pr_day_UKESM1-0-LL_ssp245_r1i1p1f2_gn_2015.nc?var=pr&north=52&west=0&east=1&south=51&horizStride=1&time_start=2015-01-01T12%3A00%3A00Z&time_end=2015-12-31T12%3A00%3A00Z&timeStride=1&vertStride=1&accept=netcdf3), created manually with the [grid service](https://ds.nccs.nasa.gov/thredds/ncss/grid/AMES/NEX/GDDP-CMIP6/UKESM1-0-LL/ssp245/r1i1p1f2/pr/pr_day_UKESM1-0-LL_ssp245_r1i1p1f2_gn_2015.nc/dataset.html)) fails with an error:
`IllegalArgumentException: Illegal base time specification: &#39;2015-12-31&#39; Value 31 for dayOfMonth must be in the range [1,30]`.

I would guess there isn't an easy solution to this, except checking the limits from the dataset.xml url and using them?

**Comment by jonathanqv** [comment]
@tbloch1 this is a dataset error I also found. But if you check the time series you will find 365/366 days, usually an extra day in February like February 29/30 or something else. With the script I don't create a filter based on dates, I pull all the data available.

**Comment by tbloch1** [comment]
The problem is that the links produced give errors rather than returning the .nc files.

E.g., [this link](https://ds.nccs.nasa.gov/thredds/ncss/grid/AMES/NEX/GDDP-CMIP6//UKESM1-0-LL/ssp245/r1i1p1f2/pr/pr_day_UKESM1-0-LL_ssp245_r1i1p1f2_gn_2015.nc?var=pr&north=1&west=51&east=52&south=0&disableProjSubset=on&horizStride=1&time_start=2015-01-01T12%3A00%3A00Z&time_end=2015-12-31T12%3A00%3A00Z&timeStride=1&addLatLon=true) produced by the script (code below) takes you to the error.

If for example I change "time_end=2015-12-31T12%3A00%3A00Z" to "time_end=2016-1-1T0%3A00%3A00Z" it correctly downloads the 2015 file.

Note, no data is downloaded for UKESM1-0-LL, and I suspect this is the reason.

This is my script:
``` python
from cmip6d import cmip6d

out_path = '/root/Data/test'                # Defines your output folder
coords = [0, 1, 51, 52]                     # xmin,xmax,ymin,ymax
models = ['GFDL-ESM4', 'UKESM1-0-LL']       # If empty, downloads everything, if not, downloads specified packages
ssp = ['ssp245','ssp585']                   # Target scenarios from the NASA server
variables = ['pr','tasmax','tasmin']        # Target variables from the NASA server

cc = cmip6d(out_path,coords,models,variables=variables,ssp=ssp)

cc.get_links(out_path,check_links=True)

cc.download_links(nworker=16)
```

Which outputs:

```
Starting GFDL-ESM4
Starting UKESM1-0-LL

 Completed GFDL-ESM4 ssp245 tasmin

 Completed GFDL-ESM4 ssp245 pr

 Completed GFDL-ESM4 ssp245 tasmax

 Completed GFDL-ESM4 ssp585 tasmin

 Completed GFDL-ESM4 ssp585 pr

 Completed GFDL-ESM4 ssp585 tasmax

 Downloading UKESM1-0-LL ssp245 tasmin
Removed model UKESM1-0-LL
```

**Comment by jonathanqv** [comment]
I have updated the script to allow these files in the downloading process. Let me know if you have problems. I think I considered these as "bad datasets" for my research, that is why these were being removed.
